### ISSUE TITLE
Add PDF or EPS versions of schematics

### ISSUE THREAD

**Issue by herbertp** [timvideos/HDMI2USB-numato-opsis-docs#3]
Vector document versions of schematic files (PDF, EPS, SVG) can be easily viewed without the need for special software. They can also be linked and used directly in the HTML pages to document certain aspects.

**Comment by mithro** [comment]
PDF version of the schematics are now available in https://github.com/timvideos/HDMI2USB-numato-opsis-docs/blob/gh-pages/pdfs/

The one you are looking for the "preproduction board" is ->
https://github.com/timvideos/HDMI2USB-numato-opsis-docs/blob/gh-pages/pdfs/NumatoOpsis-schematic-v2-prototype-13-gb1c4312.pdf
